### ISSUE TITLE
Remove anomvalidate module

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/adaptive-alerting#235]
We've decided to limit AA's scope to time series anomaly detection and have validation occur as a separate step in the pipeline, outside of AA. Therefore we need to remove the anomvalidate module.

**Comment by klymenkoo** [comment]
I can work on it if you don't mind.

**Comment by williewheeler** [comment]
@klymenkoo Yeah, absolutely, that would be great. Thanks!
