### ISSUE TITLE
Integration with AWS SageMaker DeepAR models

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/adaptive-alerting#241]
We would like to perform anomaly detection based on DeepAR prediction models:

https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html

This should be implemented as an external detector, linked in with a virtual detector.

**Comment by tkamenov-expedia** [comment]
Can I do this one too?

**Comment by williewheeler** [comment]
Closing, as this would be external to AA.
